### Get all component files
GET http://localhost:5253/api/robot-configs/components
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X3VzZXJfaWQiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJuYmYiOjE3MzcyNjk1MTQsImV4cCI6MTczNzg3NDMxNCwiaWF0IjoxNzM3MjY5NTE0LCJpc3MiOiJWaXN1YWxGbG93IiwiYXVkIjoidmlzdWFsZmxvdy1jbGllbnQifQ.AE0nfTwgJMVS-eC9gVqGWGqY42xBzmFEFQXVbBXXZ5Y
